const { ethers, artifacts } = require("hardhat");
const fs = require("fs");
const path = require("path");

//deploys TicketToken to whatever network hardhat is pointed at
//then auto-writes the contract address + ABI into frontend/js/config.js
async function main() {
    const [deployer] = await ethers.getSigners();

    console.log("deploying with account:", deployer.address);

    const balance = await ethers.provider.getBalance(deployer.address);
    console.log("account balance:", ethers.formatEther(balance), "ETH");

    //100 whole tickets at 0.01 SETH each <- adjust these for your event
    const INITIAL_SUPPLY = 100n;
    const TICKET_PRICE = ethers.parseEther("0.01");

    const TicketToken = await ethers.getContractFactory("TicketToken");
    const ticket = await TicketToken.deploy(INITIAL_SUPPLY, TICKET_PRICE);
    await ticket.waitForDeployment();

    const contractAddress = await ticket.getAddress();
    const deployTx = ticket.deploymentTransaction();

    console.log("\n--- deployment complete ---");
    console.log("contract address:", contractAddress);
    console.log("deployment tx hash:", deployTx.hash);
    console.log("etherscan link: https://sepolia.etherscan.io/address/" + contractAddress);

    //read the compiled ABI from hardhat's artifact cache
    const artifact = await artifacts.readArtifact("TicketToken");
    const abi = artifact.abi;

    //write config.js so the frontend pages can find the contract immediately
    const configPath = path.join(__dirname, "..", "frontend", "js", "config.js");
    const configContent = `//auto-generated by deploy.js on ${new Date().toISOString()}
//this file is overwritten every time you run the deploy script

const CONTRACT_ADDRESS = "${contractAddress}";
const TICKET_PRICE_ETH = "0.01";
const SEPOLIA_RPC = "https://rpc.sepolia.org";
const SEPOLIA_CHAIN_ID = 11155111;

const ABI = ${JSON.stringify(abi, null, 2)};
`;

    fs.writeFileSync(configPath, configContent);
    console.log("\nconfig.js written to frontend/js/config.js");
    console.log("update the transaction links in your report using the values above");
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
